name: openjpeg_dart_ffi_demo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  image: ^4.1.3

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^2.1.0
  test: ^1.24.0
